trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: buildPush
    displayName: 'Deploy Nuget'
    jobs:
      - job: buildAndPush
        displayName: 'Build and Publish'
        steps:
        - task: NuGetAuthenticate@1
          displayName: 'Authenticate to NuGet'

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: '**/**.csproj'
            feedsToUse: 'config'
            nugetConfigPath: 'nuget.config'
            noCache: true

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/**.csproj'
            arguments: '--configuration Release'

        - task: DotNetCoreCLI@2
          displayName: Package
          inputs:
            command: "pack"
            projects: '**/RTLS.Common.csproj'
            nobuild: true
            configuration: "Release"
            versioningScheme: "off"

        - task: DotNetCoreCLI@2
          displayName: Push
          inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: '4630136d-be08-48b6-9030-7d0af08008c5/dc097e14-fd70-4bd5-b7f9-92941a543baa'

